name: "Deployment to GitHub Pages on push"
on:
  workflow_dispatch:
    push:
      branches:
        - main
jobs:
#  delete-gh-pages:
#    runs-on: ubuntu-latest
  install-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: "Install npm"
        run: npm install
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: "Build project"
        run: npm run build
  add-and-commit-dist:
    runs-on: ubuntu-latest
    steps:
      - name: "Add dist folder to Git"
        run: git add dist -f
      - name: "Commit dist folder to Git"
        run: git commit -m "Updating deployment on pushed version."
  push-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy to gh-pages branch"
        run: git subtree push --prefix dist origin gh-pages